image: fedora:30

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

build:
  stage: build
  retry: 0
  script:
    - dnf install -y make gcc gcc-c++ git libusb-devel cmake hidapi-devel meson
    - git submodule update --init --recursive
    - mkdir -p build-cmake
    - cd build-cmake && cmake -DCMAKE_BUILD_TYPE=Release ..
    - cd build-cmake && make
    - meson build-meson && cd build-meson && ninja
    - make
#    - tar zcvf artifacts.tar.gz ./
#    - find . | grep "hotp.verification" | xargs sha256sum

#  artifacts:
#    paths:
#      - ./artifacts.tar.gz
